# fly.toml app configuration file generated for exofront-game on 2026-06-10T22:24:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exofront-game'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
